### PR TITLE
docs: rename Actual True Range to Average True Range

### LINKED ISSUE #359: Docs: "Actual" True Range instead of "Average" True Range
A minor thing I noticed in the docs: The `atr` indicator is titled "Actual True Range", within the code itself it is described as what I also knew beforehand as "Average True Range", so I guess it is just a typo.

**To Reproduce**

1. Go to [atr docs](https://github.com/cinar/indicatorts/blob/main/src/indicator/volatility/index.md#actual-true-range-atr)
1. Read headline
1. Be a bit confused that it is called "Actual True Range"
4. Go to code and see that [it is described as "Average True Range" there](https://github.com/cinar/indicatorts/blob/main/src/indicator/volatility/atr.ts#L16).

**Expected behavior**
Docs should have the correct name, I guess? 😄

### PR DESCRIPTION
**Pull request by HerrBertling**
As described in #359, I think the indicator name is slightly wrong in the docs, but correct in the code itself.

This adjusts the docs accordingly.

Closes #359

# Describe Request

Please describe your request.

Fixed # (issue)

# Change Type

What is the type of this change.

### CODE REVIEW

**Comment by cinar** [comment]
Thank you very much! Good catch! One minor comment, if you can make that quick change, I'll merge this right after. Many thanks!

**Comment by HerrBertling** [comment]
> One minor comment, if you can make that quick change

I just got around to checking this PR on my laptop, I thought I'd just not see the comment on my phone. But… I can't see any comment 😄  Can you check again if you have sent it?

**Comment by cinar** [comment]
It is actually at the top, let me copy it here:

In [src/indicator/volatility/index.md](https://github.com/cinar/indicatorts/pull/360/files/2637cd7c9f4547b2eddf99b3623f4fb9325ed01c#diff-f134fef52de644fcdaffb59bfb17e5350f174495af1c7fc17c42f2b4d9eb624e) could you also update the link target to also point at the right section?

```
- [Actual True Range (ATR)](#actual-true-range-atr)
- [Average True Range (ATR)](#actual-true-range-atr)
```

Not a big deal, I can also fix it after merging, but just wanted to check if you make that quick change and then I can merge?

**Comment by HerrBertling** [comment]
Yes sure, I’ll check tomorrow and update that part.

**Comment by HerrBertling** [comment]
Done :)

**Pull request merged**
